-- Real Estate Management System
-- Database Schema (PostgreSQL)

CREATE TABLE IF NOT EXISTS public.agencies (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(250),
    authorized_person VARCHAR(100) NOT NULL,
    business_name VARCHAR(150) NOT NULL,
    fax VARCHAR(20),
    phone VARCHAR(20),
    CONSTRAINT agencies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_type VARCHAR(30) NOT NULL,
    email VARCHAR(150),
    first_name VARCHAR(100) NOT NULL,
    home_phone VARCHAR(20),
    last_name VARCHAR(100) NOT NULL,
    mobile_phone VARCHAR(20),
    notes VARCHAR(500),
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_customer_type_check
        CHECK (customer_type IN ('BUYER', 'SELLER', 'OWNER'))
);

CREATE TABLE IF NOT EXISTS public.properties (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(250),
    building_floors INTEGER,
    city VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    district VARCHAR(100),
    floor_number INTEGER,
    furnished BOOLEAN,
    heating_type VARCHAR(30),
    listing_type VARCHAR(20) NOT NULL,
    price DOUBLE PRECISION,
    property_type VARCHAR(30) NOT NULL,
    room_count INTEGER,
    square_meters INTEGER,
    status VARCHAR(20) NOT NULL,
    title VARCHAR(150) NOT NULL,
    owner_customer_id BIGINT NOT NULL,
    CONSTRAINT properties_pkey PRIMARY KEY (id),
    CONSTRAINT properties_owner_customer_fk
        FOREIGN KEY (owner_customer_id)
        REFERENCES public.customers (id),
    CONSTRAINT properties_heating_type_check
        CHECK (heating_type IN ('NATURAL_GAS', 'CENTRAL', 'STOVE', 'AIR_CONDITIONER')),
    CONSTRAINT properties_listing_type_check
        CHECK (listing_type IN ('RENT', 'SALE')),
    CONSTRAINT properties_property_type_check
        CHECK (property_type IN ('APARTMENT', 'HOUSE', 'OFFICE', 'LAND')),
    CONSTRAINT properties_status_check
        CHECK (status IN ('ACTIVE', 'RENTED', 'SOLD', 'PASSIVE'))
);

CREATE TABLE IF NOT EXISTS public.property_search_requests (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city VARCHAR(100),
    district VARCHAR(100),
    furnished BOOLEAN,
    heating_type VARCHAR(30),
    listing_type VARCHAR(20),
    max_price DOUBLE PRECISION,
    max_room_count INTEGER,
    max_square_meters INTEGER,
    min_price DOUBLE PRECISION,
    min_room_count INTEGER,
    min_square_meters INTEGER,
    property_type VARCHAR(30),
    customer_id BIGINT NOT NULL,
    CONSTRAINT property_search_requests_pkey PRIMARY KEY (id),
    CONSTRAINT property_search_requests_customer_fk
        FOREIGN KEY (customer_id)
        REFERENCES public.customers (id),
    CONSTRAINT property_search_requests_heating_type_check
        CHECK (heating_type IN ('NATURAL_GAS', 'CENTRAL', 'STOVE', 'AIR_CONDITIONER')),
    CONSTRAINT property_search_requests_listing_type_check
        CHECK (listing_type IN ('RENT', 'SALE')),
    CONSTRAINT property_search_requests_property_type_check
        CHECK (property_type IN ('APARTMENT', 'HOUSE', 'OFFICE', 'LAND'))
);